/**
 * Bot filtering (vendored, isbot-style). A missing or matching user agent is
 * dropped at the ingestion edge before any DB work.
 */

const BOT_PATTERN = new RegExp(
  [
    "bot",
    "crawl",
    "spider",
    "slurp",
    "headless",
    "lighthouse",
    "phantomjs",
    "selenium",
    "puppeteer",
    "playwright",
    "electron",
    "wget",
    "curl",
    "python-requests",
    "python-urllib",
    "aiohttp",
    "httpclient",
    "okhttp",
    "go-http-client",
    "java/",
    "libwww",
    "scrapy",
    "facebookexternalhit",
    "whatsapp",
    "telegram",
    "discordapp",
    "slackbot",
    "twitterbot",
    "linkedinbot",
    "pinterest",
    "bingpreview",
    "vkshare",
    "petalbot",
    "semrush",
    "ahrefs",
    "mj12",
    "dotbot",
    "applebot",
    "yandex",
    "baiduspider",
    "duckduckbot",
    "googlebot",
    "adsbot",
    "apis-google",
    "mediapartners",
    "feedfetcher",
    "google-read-aloud",
    "storebot",
    "gptbot",
    "ccbot",
    "claudebot",
    "claude-web",
    "anthropic",
    "perplexity",
    "bytespider",
    "amazonbot",
    "dataforseo",
    "uptimerobot",
    "uptime-kuma",
    "pingdom",
    "statuscake",
    "site24x7",
    "newrelic",
    "datadog",
    "checkly",
    "monitor",
    "scanner",
    "archive.org",
    "ia_archiver",
    "prerender",
    "rendertron",
    "html2pdf",
    "pdfshift",
  ].join("|"),
  "i",
);

export function isBot(userAgent: string | null | undefined): boolean {
  if (!userAgent || userAgent.trim() === "") return true;
  return BOT_PATTERN.test(userAgent);
}
