-- 0000 BASELINE - legacy schema snapshot (reconstruction)
--
-- The production Supabase project predates version-controlled migrations: its
-- tables and RPCs were created in the dashboard. This migration reproduces that
-- schema so a fresh database (local dev, CI) matches production. It is written
-- to be idempotent; when the Supabase CLI is linked to the production project,
-- mark it as applied with `supabase migration repair --status applied 20260703000000`
-- instead of running it.
--
-- Sources: lib/database.types.ts (generated types), app/api/track/route.ts,
-- app/api/events/route.ts, lib/actions/analytics.ts.

create extension if not exists pgcrypto;

-- App users (mirror of auth.users maintained by the app; `api` is the Bearer
-- key for POST /api/events).
create table if not exists public.users (
    id uuid primary key,
    email text not null,
    full_name text,
    api text,
    created_at timestamptz default now(),
    updated_at timestamptz
);

-- Registered domains, flat per-user tenancy.
create table if not exists public.domains (
    id uuid primary key default gen_random_uuid(),
    domain text not null,
    user_id uuid not null,
    created_at timestamptz not null default now()
);

-- One row per session_start beacon.
create table if not exists public.visits (
    id bigint generated by default as identity primary key,
    website_id text,
    source text,
    visitor_id text,
    session_id text,
    device_type text,
    os text,
    country text,
    screen_width integer,
    screen_height integer,
    language text,
    utm_source text,
    utm_medium text,
    utm_campaign text,
    created_at timestamptz not null default now()
);

-- One row per pageview beacon.
create table if not exists public.page_views (
    id bigint generated by default as identity primary key,
    domain text,
    page text,
    visitor_id text,
    session_id text,
    device_type text,
    os text,
    country text,
    created_at timestamptz not null default now()
);

-- Legacy custom events (POST /api/events).
create table if not exists public.events (
    id bigint generated by default as identity primary key,
    event_name text not null,
    website_id text not null,
    message text,
    created_at timestamptz not null default now()
);

-- Non-atomic daily rollup maintained by app/api/track/route.ts.
-- The route reads a single row per (domain, date) with .single().
create table if not exists public.daily_stats (
    id bigint generated by default as identity primary key,
    domain text not null,
    date date not null,
    visits integer not null default 0,
    unique_visitors integer not null default 0,
    page_views integer not null default 0,
    created_at timestamptz not null default now(),
    unique (domain, date)
);

create index if not exists visits_website_created_idx on public.visits (website_id, created_at);
create index if not exists page_views_domain_created_idx on public.page_views (domain, created_at);
create index if not exists events_website_created_idx on public.events (website_id, created_at);

-- Aggregation RPCs used by lib/actions/analytics.ts (previously dashboard-only).
create or replace function public.get_device_stats(
    website_domain text,
    start_date timestamptz,
    end_date timestamptz
) returns table (device_type text, count bigint)
language sql stable
as $$
    select v.device_type, count(*)::bigint as count
    from public.visits v
    where v.website_id = website_domain
      and v.created_at >= start_date
      and v.created_at <= end_date
    group by v.device_type
    order by count desc;
$$;

create or replace function public.get_country_stats(
    website_domain text,
    start_date timestamptz,
    end_date timestamptz
) returns table (country text, count bigint)
language sql stable
as $$
    select v.country, count(*)::bigint as count
    from public.visits v
    where v.website_id = website_domain
      and v.created_at >= start_date
      and v.created_at <= end_date
    group by v.country
    order by count desc;
$$;

create or replace function public.get_os_stats(
    website_domain text,
    start_date timestamptz,
    end_date timestamptz
) returns table (os text, count bigint)
language sql stable
as $$
    select v.os, count(*)::bigint as count
    from public.visits v
    where v.website_id = website_domain
      and v.created_at >= start_date
      and v.created_at <= end_date
    group by v.os
    order by count desc;
$$;
